version: '3'

services:
  web:
    container_name: fastapi-project
    image: fastapi-project
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    restart: always
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
      - db

  redis:
    container_name: redis_db
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432

volumes:
  postgres_data:
  redis_data:

