version: '3'

services:
  api:
    build: .
    container_name: fastapi-project
    image: myimage
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    expose:
      - 8000
#    depends_on:
#      - redis
#
#  redis:
#    container_name: redis
#    image: redis
#  db:
#    container_name: postgres
#    image: postgres
#    env_file:
#      - database.env
