version: '3.9'

services:
  web:
    container_name: fastapi-project
    image: fastapi-project
    build: .
    command: uvicorn src.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/src/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  redis:
    container_name: redis_db
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  db:
    container_name: postgresql
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOSTNAME}
    ports:
      - 5432:5432

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/postgres?sslmode=disable
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data:
